# doesnt need anything because we are using the default configuration from the board
<<<<<<< HEAD
CONFIG_COMPILER_OPT="-mlongcalls"
=======
# CONFIG_COMPILER_OPT="-mlongcalls"

# Core kernel + logging/print
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# GPIO (for LED blink)
CONFIG_GPIO=y

# UART console (needed for printk over serial)
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y

# Display configuration
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_ILI9340=y

>>>>>>> 796d1c7 (Blue screen shows kinda)
